const customers = [
  {
    id: 1001,
    name: "John",
    lastname: "Smith",
    email: "john.smith@example.com",
    phone: "+1 202 555 0111",
    address: "New York, USA",
  },
  {
    id: 5012,
    name: "Emily",
    lastname: "Johnson",
    email: "emily.johnson@example.com",
    phone: "+44 20 7946 0012",
    address: "London, UK",
  },
  {
    id: 2303,
    name: "Michael",
    lastname: "Brown",
    email: "michael.brown@example.com",
    phone: "+61 2 9374 1234",
    address: "Sydney, Australia",
  },
  {
    id: 1304,
    name: "Sophia",
    lastname: "Martinez",
    email: "sophia.martinez@example.com",
    phone: "+34 91 123 4567",
    address: "Madrid, Spain",
  },
  {
    id: 9505,
    name: "David",
    lastname: "Wilson",
    email: "david.wilson@example.com",
    phone: "+49 30 1234 5678",
    address: "Berlin, Germany",
  },
  {
    id: 4376,
    name: "Olivia",
    lastname: "Taylor",
    email: "olivia.taylor@example.com",
    phone: "+33 1 44 55 66 77",
    address: "Paris, France",
  },
  {
    id: 3907,
    name: "James",
    lastname: "Anderson",
    email: "james.anderson@example.com",
    phone: "+1 310 555 0199",
    address: "Los Angeles, USA",
  },
  {
    id: 2488,
    name: "Isabella",
    lastname: "Harris",
    email: "isabella.harris@example.com",
    phone: "+39 06 1234 5678",
    address: "Rome, Italy",
  },
  {
    id: 5609,
    name: "William",
    lastname: "Clark",
    email: "william.clark@example.com",
    phone: "+81 3 1234 5678",
    address: "Tokyo, Japan",
  },
  {
    id: 7810,
    name: "Mia",
    lastname: "Lewis",
    email: "mia.lewis@example.com",
    phone: "+55 11 98765 4321",
    address: "São Paulo, Brazil",
  },
];

export default customers;
